### ISSUE TITLE
Outline comparison between this port and InstantWebP2P Port

### ISSUE THREAD

**Issue by Downchuck** [ianopolous/tweetnacl-java#1]
There appears to be a pure-Java port (MIT Licensed) here:
https://github.com/InstantWebP2P/tweetnacl-java

It'd be nice to see some remarks as to the differences between the two projects. Clearly, the JNI interface is one.

**Comment by ian-gtv** [comment]
At the time of porting we had found some errors in the InstantWebP2P port compared to the native C, and rather than debug that port we reported from the original C. our port has been verified compared to the original C and dchest's Javascript port for message of length up to 2^24 bytes.

**Comment by ianopolous** [comment]
At the time of porting we had found some errors in the InstantWebP2P port compared to the native C, and rather than debug that port we reported from the original C. our port has been verified compared to the original C and dchest's Javascript port for message of length up to 2^24 bytes.
