### ISSUE TITLE
crypto_sign_open() does not verify signature

### ISSUE THREAD

**Issue by franslundberg** [ianopolous/tweetnacl-java#2]
It seems like the crypto_sign_open() method does not verify the signature correctly (or not at all). The result code from TweetNaCl.crypto_sign_open(message, signed, signed.length, publicSigningKey) is not used. There seem to be some other issue as well. Even when I change code as seen below, the method does not signal "bad signature" when the message is modified after signing.

```
public static byte[] crypto_sign_open(byte[] signed, byte[] publicSigningKey) {
    byte[] message = new byte[signed.length];
    // WAS: TweetNaCl.crypto_sign_open(message, signed, signed.length, publicSigningKey);

    // CHANGED to
    int resultCode = TweetNaCl.crypto_sign_open(message, signed, signed.length, publicSigningKey);
    if (resultCode != 0) {
        throw new RuntimeException("bad signature");
    }
    return Arrays.copyOfRange(message, 64, message.length);
}
```

**Comment by ianopolous** [comment]
Well spotted! I've made sure that unbox and unsign throw exceptions for invalid ciphertext or signatures now.

**Comment by franslundberg** [comment]
Great, that was fast :-). Thank you. / Frans

**Comment by ianopolous** [comment]
No, we should be thanking you!
