### ISSUE TITLE
Smells a little

### ISSUE THREAD

**Issue by pcarrier** [ianopolous/tweetnacl-java#7]
![image](https://user-images.githubusercontent.com/8641/82517438-1ba4d200-9aeb-11ea-83c1-aaf54ca863d9.png)

**Comment by ianopolous** [comment]
The same is present in the original C from DJB. So if there's a problem here, there's a problem with DJB's version.
https://github.com/ianopolous/tweetnacl-java/blob/master/native/tweetnacl.c#L532
